apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pagerduty-provider.yaml
  - pagerduty-alert.yaml
  - rocket-chat-provider.yaml
  - rocket-chat-alert.yaml
patches:
  - patch: |
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --no-cross-namespace-refs=true      
    target:
      kind: Deployment
      name: "(notification-controller)"
