apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: pagerduty-alert
  namespace: default
spec:
  summary: "cluster addons"
  eventMetadata:
    env: "production"
    cluster: "my-cluster"
    region: "us-east-2"
  providerRef:
    name: pagerduty
  eventSeverity: error
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
