apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: rocket-chat-alert
  namespace: notifications
spec:
  summary: "cluster addons"
  # eventMetadata:
    # env: "production"
    # cluster: "my-cluster"
    # region: "us-east-2"
  providerRef:
    name: rocket-chat-provider
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
