apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rocket-chat-notifier-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rocket-chat-notifier-binding
subjects:
  - kind: ServiceAccount
    name: rocket-chat-notifier-sa
    namespace: infrastructure
roleRef:
  kind: ClusterRole
  name: rocket-chat-notifier-role
  apiGroup: rbac.authorization.k8s.io
