apiVersion: v1
kind: Service
metadata:
  name: tempo-service
  namespace: monitoring
  labels:
    app: tempo
spec:
  ports:
    - name: http
      port: 3200
      targetPort: 3200
    - name: grpc
      port: 4317
      targetPort: 4317
  selector:
    app: tempo
  type: ClusterIP

