apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: acls.msk.aws.io
spec:
  group: msk.aws.io
  names:
    kind: ACL
    listKind: ACLList
    plural: acls
    singular: acl
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                clusterArn:
                  type: string
                topicName:
                  type: string
                principal:
                  type: string
                operation:
                  type: string
                permission:
                  type: string
