apiVersion: apps/v1
kind: Deployment
metadata:
  name: audi-operator
  namespace: default
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: ''
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audi-operator
  template:
    metadata:
      labels:
        app: audi-operator
    spec:
      containers:
        - name: audi-operator
          image: audi-operator:latest
          envFrom:
            - configMapRef:
                name: msk-config
          volumeMounts:
            - mountPath: /certificates
              name: msk-certificates
              readOnly: true
      volumes:
        - name: msk-certificates
          secret:
            secretName: msk-certificates
