apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: test-container
      image: alpine:latest
      command: ['/bin/sh', '-c', 'env && sleep 3600']
      envFrom:
        - configMapRef:
            name: msk-config
