auth_enabled: true
server:
  http_listen_port: 9009
distributor:
  ring:
    kvstore:
      store: inmemory
    replication_factor: 1
limits:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
