apiVersion: v1
kind: Service
metadata:
  name: mimir-service
  namespace: monitoring
  labels:
    app: mimir
spec:
  ports:
    - port: 9009
      targetPort: 9009
      protocol: TCP
      name: http
  selector:
    app: mimir
  type: ClusterIP

