
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 10m
  path: "./clusters/your-cluster-name/grafana"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: grafana
