apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rdsinstances.aws.audi.de
spec:
  group: aws.audi.de
  names:
    kind: RDSInstance
    listKind: RDSInstanceList
    plural: rdsinstances
    singular: rdsinstance
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
                description: "The name of the database."
              stage:
                type: string
                enum:
                  - pre-live
                  - dev
                  - int
                description: "Environment for the DB (pre-live, dev, int)."
              engine:
                type: string
                enum:
                  - postgres
                  - mysql
                description: "DB engine (PostgreSQL or MySQL)."
              instanceClass:
                type: string
                description: "AWS RDS instance class."
              allocatedStorage:
                type: integer
                minimum: 20
                description: "Allocated storage size (in GB)."
              username:
                type: string
                description: "Master username for the DB."
